---
- hosts: servers
  become: true

  vars:
    golang_version: 1.25.0

  tasks:

    - name: "Update and upgrade apt"
      apt:
        upgrade: dist
        update_cache: true

    - name: "Install git"
      apt:
        name: git
        state: latest

    - name: "Download golang"
      get_url:
        url: "https://golang.org/dl/go{{ golang_version }}.linux-amd64.tar.gz"
        dest: "/tmp/go{{ golang_version }}.tar.gz"
        mode: "0644"

    - name: "Extract Golang"
      unarchive:
        src: "/tmp/go{{ golang_version }}.tar.gz"
        dest: "/usr/local"
        remote_src: true
        owner: root
        group: root

    - name: Create symlink for GO
      file:
        path: /usr/bin/go
        src: /usr/local/go/bin/go
        state: link
        owner: root
        group: root

    - name: Set GOPATH
      lineinfile:
        path: /etc/profile
        line: "export GOPATH=$HOME/go"
        state: present

    - name: Apply changes
      command:
        argv:
          - /bin/bash
          - -c
          - "source /etc/profile"
      changed_when: false

    - name: Verify Git installation
      command: git --version
      register: git_version
      changed_when: false

    - name: Verify Go installation
      command:
        argv:
          - /bin/bash
          - -c
          - "go version"
      register: go_version
      changed_when: false

    - name: Show results
      debug:
        msg:
          - "Git version: {{ git_version.stdout }}"
          - "Go version: {{ go_version.stdout }}"
...
